// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  resume: dynamic(() => import("./Resume")),
  services: dynamic(() => import("./Services")),
  work: dynamic(() => import("./Work")),
};
